# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: "#about"
    weight: 10
  - name: Contact
    url: "#contact"
    weight: 20
  - name: Blog++
    identifier: "writing"
    weight: 30
  - name: Blog
    url: "/post/"
    parent: "writing"
    weight: 110
  - name: Data Structures & Algorithms
    url: "/dsa/"
    parent: "writing"
    weight: 115
  - name: Leetcode solution
    url: "/leetcode/"
    parent: "writing"
    weight: 120
  - name: Hackerrank solution
    url: "/hackerrank/"
    parent: "writing"
    weight: 130
  - name: Codesignal solution
    url: "/codesignal/"
    parent: "writing"
    weight: 140
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
